ALTER TABLE users
ADD COLUMN IF NOT EXISTS location TEXT,
ADD COLUMN IF NOT EXISTS bio TEXT,
ADD COLUMN IF NOT EXISTS travel_style TEXT,
ADD COLUMN IF NOT EXISTS languages JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS newsletter BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS safety_alerts BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS theme_color TEXT DEFAULT '#0E8C88';
